Zoomed description of a product
zeachco/rockplusinc.com pull request #1
Opened 2016-11-02 19:24 UTC by Megahand

2016-11-02 19:25 UTC, Megahand commented
![](https://github.trello.services/images/mini-trello-icon.png) [rockplusinc.com Email de Mike : Zoomed description of a product](https://trello.com/c/N3chAI5I/7-rockplusinc-com-email-de-mike-zoomed-description-of-a-product)

2016-11-02 19:35 UTC, zeachco requested changes
small modification before merge
also if you can include a small image of the changes in the description
that would be awesome :smile:

2016-11-02 19:35 UTC, zeachco commented on src/styles/_item-details.scss
> +
might be good to add `font-weight: 700; color: black; text-shadow 0 0 1px white` for readability

2016-11-02 19:35 UTC, zeachco commented on src/components/Item/index.js
> +            <Details imgClassName={"png_alpha"} src={imgFull || NoImageAvail} thumbsSrc={imgThumb || NoImageAvail} title={name} {...props}/>
`imgClassName={"png_alpha"}` can be changed to `imgClassName="png_alpha"` (no evaluation)

2016-11-02 19:35 UTC, zeachco commented on src/components/Item/Details/index.js
> +          <div className={'info'}>
`<div className={'info'}>` can be changed to `<div className="info">`

2016-11-03 02:59 UTC, zeachco approved these changes

2016-11-03 03:00 UTC, zeachco commented
@Megahand I've pushed some changes addressing my comments

2016-11-03 03:05 UTC, merged